export const jwtConstants={
    SECRET:'thesecretkey' 
}

export const BOOKING_RESPONSE={
    BOOKING:'BOOKING SUCCESSFULLY',
    BOOKING_NOT_FOUND:'BOOKING NOT FOUND',
    ERROR_GET_ALL_BOOKING:'ERROR TO GET ALL BOOKING',
    ERROR_BOOKING:'ERROR TO BOOKING MOVIE TICKET ',
    GET_ALL_BOOKING:'ALL BOOKING FATCH SUCCESSFULLY',
    GET_BOOKING_BY_ID:'BOOKING FATCH  SUCCESSFULLY',
    ERROR_BOOKING_BY_ID:'ERROR RETRIEVING BOOKING ',
    UPDATE_BOOKING:'BOOKING UPDATE SUCCESSFULLY',
    ERROR_UPDATE_BOOKING:'ERROR TO UPDATE BOOKING',
    DELETE_BOOKING:'BOOKING DELETE SUCCESSFULLY',
    ERROR_DELETE_BOOKING:'ERROR TO DELETE BOOKING',
    NOT_AUTHORIZED:'YOU ARE NOT VALID USER FOR THIS ACTION!'
}
